import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import Navbarheader from "../components/Navbarheader";
import Logo from "../components/Logo";
import Footer from "../components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbarheader />
        <Logo />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
